POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer TODO 

{
  "title": "Fabian's Blog",
  "author": "Fabian",
  "url": "https://fabiansteuer.com",
  "likes": 1 
}